# Recover the full saved No. 74 lattice group once, then restrict it to the
# unique No. 78 subgroup.  The symplectic part changes from D8 to C4.

include(joinpath(@__DIR__, "restriction_functions.jl"))

const began78 = time()
function note78(message)
    println(round(time() - began78; digits=1), " s | ", message)
    flush(stdout)
end

# D8 has a unique C4.  In the full parent group, find every D8 generated by
# that C4 and an involution outside the symplectic D8.  Compare actual element
# sets, since the same subgroup occurs for several choices of involution.
function unique_child_78(H, N)
    rotations = [x for x in elements(N) if order(x) == 4]
    @assert length(rotations) == 2
    c4 = first(rotations)
    C4, _ = sub(H, [c4])
    @assert order(C4) == 4

    all_h = collect(elements(H))
    candidates = []
    membership = Vector{Bool}[]
    for b in all_h
        (b in N || order(b) != 2) && continue
        B, _ = sub(H, [c4, b])
        order(B) == 8 || continue
        small_group_identification(B) == (8, 3) || continue
        overlap = [x for x in elements(B) if x in N]
        length(overlap) == 4 || continue
        all(x -> x in C4, overlap) || continue
        key = [x in B for x in all_h]
        if !any(old -> old == key, membership)
            push!(candidates, B)
            push!(membership, key)
        end
    end
    @assert length(candidates) == 1
    B = only(candidates)
    extra = first(x for x in elements(B) if !(x in C4))
    @assert order(extra) == 2
    @assert !(extra in N)
    @assert length([x for x in elements(B) if x in N]) == 4
    return B, c4, extra
end

source = load(joinpath(@__DIR__, "..", "..", "oscar", "oscar_script_data.mrdi"))
@assert source.cases[29].case_index == 29
@assert source.cases[29].number_of_results >= 1
parent = source.cases[29].results[1]
@assert parent.order == 2 && parent.dimension == 4
@assert parent.group_gap_id == (16, 11)
L = lattice(parent.Lambda0)
S = lattice(parent.S_in_Lambda0)
T = lattice(parent.T_in_Lambda0)
@assert rank(L) == 22 && rank(S) == 15 && rank(T) == 7
@assert order_of_isometry(parent.Lambda0) == 2
note78("Loaded No. 74 from case 29 result 1")

# The saved extension includes its extra isometry, but not generators for the
# stable discriminant kernel of S.  Those generators extend by the identity
# on the rational orthogonal complement and preserve the ambient gluing.
cache_path = joinpath(@__DIR__, "source_74_full_lattice_group.mrdi")
if isfile(cache_path)
    cache = load(cache_path)
    @assert cache.parent_number == 74
    @assert gram_matrix(lattice(cache.Lambda0)) == gram_matrix(L)
    @assert basis_matrix(lattice(cache.Lambda0)) == basis_matrix(L)
    @assert isometry(cache.Lambda0) == isometry(parent.Lambda0)
    @assert basis_matrix(lattice(cache.S_in_Lambda0)) == basis_matrix(S)
    @assert cache.extra_generator == isometry(parent.Lambda0)
    @assert cache.full_group_id == (16, 11)
    lifts = cache.symplectic_generators
    note78("Loaded cached ambient D8 generators")
else
    note78("Computing O(S_74) generators")
    O = matrix_group(automorphism_group_generators(S; ambient_representation=false))
    rho = discriminant_representation(S, O;
        ambient_representation=false, full=false, check=true)
    K, inclusion = kernel(rho)
    @assert order(K) == 8 && small_group_identification(K) == (8, 3)
    lifts = typeof(isometry(parent.Lambda0))[]
    for u in gens(K)
        Su = integer_lattice_with_isometry(S, matrix(inclusion(u));
            ambient_representation=false, check=true)
        Lu = integer_lattice_with_isometry(L, ambient_isometry(Su);
            ambient_representation=true, check=true)
        push!(lifts, isometry(Lu))
    end
    note78("Recovered D8 generators in the parent Lambda0 basis")
end

H = matrix_group(vcat(lifts, [isometry(parent.Lambda0)]))
N, _ = sub(H, [H(a) for a in lifts])
@assert order(H) == 16 && small_group_identification(H) == (16, 11)
@assert order(N) == 8 && small_group_identification(N) == (8, 3)
@assert all(h * n * inv(h) in N for h in elements(H), n in elements(N))
if !isfile(cache_path)
    save(cache_path, (
        parent_number=74,
        source="oscar/oscar_script_data.mrdi case 29 result 1",
        Lambda0=parent.Lambda0,
        S_in_Lambda0=parent.S_in_Lambda0,
        symplectic_generators=lifts,
        extra_generator=isometry(parent.Lambda0),
        full_group_id=(16, 11),
    ))
    reloaded_cache = load(cache_path)
    @assert length(reloaded_cache.symplectic_generators) == length(lifts)
    note78("Saved and reloaded reusable No. 74 ambient generators")
end

B, c4, extra = unique_child_78(H, N)
@assert order(B) == 8 && small_group_identification(B) == (8, 3)
note78("Selected the unique D8 subgroup with C4 symplectic intersection")

function save_checked_result78(path, result;
    group_checked::Bool, roots_checked::Bool, saturation_checked::Bool)
    save(path, (
        format_version=1,
        source_file="oscar/oscar_script_data.mrdi case 29 result 1",
        construction="unique subgroup restriction No. 74 -> No. 78",
        verify_group_id=group_checked,
        verify_roots=roots_checked,
        verify_symplectic_saturation=saturation_checked,
        result=result,
    ))
    r = load(path)
    @assert r.result.parent_number == 74 && r.result.child_number == 78
    @assert r.result.order == 2 && r.result.dimension == 5
    @assert rank(lattice(r.result.S_in_Lambda0)) == 14
    @assert rank(lattice(r.result.T_in_Lambda0)) == 8
    @assert rank(r.result.P_in_Lambda0) == 7
    @assert rank(r.result.K_in_Lambda0) == 15
    @assert rank(lattice(r.result.P_action)) == 7
    @assert order_of_isometry(r.result.T_action) == 2
    @assert r.result.extracted_subgroup_id == (8, 3)
    @assert r.result.symplectic_saturation_verified == saturation_checked
    if group_checked
        @assert r.result.group_gap_id == (8, 3)
    end
    if saturation_checked
        @assert r.result.symplectic_kernel_order_S == 4
        @assert r.result.symplectic_kernel_order_K == 4
    end
end

kwargs = (
    parent_number=74,
    child_number=78,
    index=2,
    expected_rank_S=14,
    expected_dimension=5,
    expected_group_id=(8, 3),
)
precheck = complete_cyclic_restriction(
    parent, matrix(c4), matrix(extra); kwargs...,
    verify_group_id=false, verify_roots=false,
    verify_symplectic_saturation=false,
)
precheck_path = joinpath(@__DIR__, "restriction_complete_78_from_74.precheck.mrdi")
save_checked_result78(precheck_path, precheck;
    group_checked=false, roots_checked=false, saturation_checked=false)
note78("Saved full ambient S/T/P/K precheck for No. 78")

if get(ENV, "RESTRICTION_VERIFY_FULL", "1") == "1"
    note78("Checking roots and the group ID")
    verified = complete_cyclic_restriction(
        parent, matrix(c4), matrix(extra); kwargs...,
        verify_group_id=true, verify_roots=true,
        verify_symplectic_saturation=false,
    )
    full_path = joinpath(@__DIR__, "restriction_complete_78_from_74.mrdi")
    save_checked_result78(full_path, verified;
        group_checked=true, roots_checked=true, saturation_checked=false)
    note78("Saved verified complete No. 78 result")
end
