# Exhaustive C3 restrictions inside the cached full No. 67 action.
# Run the companion GAP character certificate before the named OSCAR stages.
# Neither child saturation nor uniqueness outside this parent is inferred.

using SHA
include(joinpath(@__DIR__, "restriction_101_102_from_67.jl"))

const r106_child = 106
const r106_id = (3,1)
const r106_gap_script = joinpath(@__DIR__, "restriction_106_geometric_character.g")
const r106_characters = joinpath(@__DIR__, "restriction_106_geometric_character.tsv")
const r106_groups_file = joinpath(@__DIR__, "restriction_106_from_67.groups.mrdi")
const r106_lattices_file = joinpath(@__DIR__, "restriction_106_from_67.lattices.mrdi")
const r106_verified_file = joinpath(@__DIR__, "restriction_106_from_67.verified.mrdi")

r106_note(s) = (println(s); flush(stdout))

function r106_source_hashes()
    isfile(r67_cache) || error("No. 67 full-group cache is missing")
    isfile(r106_gap_script) && isfile(r106_characters) ||
        error("Run the companion No. 106 GAP script first")
    return (r67_prepare_hashes()...,
        (basename(r67_cache),r67_hash(r67_cache)),
        (basename(r106_gap_script),r67_hash(r106_gap_script)),
        (basename(r106_characters),r67_hash(r106_characters)),
        (basename(@__FILE__),r67_hash(@__FILE__)))
end

function r106_table_check()
    r67_table_check() # Guards the cached No. 67 parent and its source records.
    found = Tuple[]
    for line in eachline(r67_table)
        startswith(line,'|') || continue
        cells = strip.(split(line,'|'))
        length(cells) >= 9 || continue
        tryparse(Int,cells[2]) == r106_child || continue
        m = match(r"\[(\d+),(\d+)\]",cells[8])
        m === nothing && error("Missing No. 106 group ID")
        push!(found,(parse(Int,cells[3]),replace(cells[4],"`"=>""),
            parse(Int,cells[5]),parse(Int,cells[6]),parse(Int,cells[7]),
            (parse(Int,m.captures[1]),parse(Int,m.captures[2]))))
    end
    found == [(12,"C3",1,1,8,r106_id)] ||
        error("No. 106 rank/group/index/dimension row changed: $found")
end

function r106_containment_check()
    matches = 0
    for (line_number,line) in enumerate(eachline(r67_edges))
        line_number == 1 && continue
        v = split(line,'\t')
        length(v) == 12 || error("Malformed strict-containment row $line_number")
        parse(Int,v[1]) == 106 && parse(Int,v[2]) == 67 || continue
        Tuple(parse.(Int,v[3:6])) == (8,2,9,108) ||
            error("Wrong direct-containment dimensions or GL orders")
        v[7:10] == ["embedded","direct","true","fail"] ||
            error("No. 106 -> 67 is not a direct strict containment")
        v[12] in ("literal_matrix_subgroup","A_strict") ||
            error("Unexpected strict-containment method")
        matches += 1
    end
    matches == 1 || error("Expected exactly one direct No. 106 -> 67 edge")
end

function r106_geometric_character()
    histogram = Dict{Tuple{Int,Int},Int}()
    for (i,line) in enumerate(eachline(r106_characters))
        if i == 1
            line == "family_number\tprojective_order\tprimitive_H4_trace\telement_count" ||
                error("Unexpected geometric-character header")
            continue
        end
        isempty(strip(line)) && continue
        v = split(line,'\t')
        length(v) == 4 || error("Malformed geometric-character row $i")
        n,ord,tr,count = parse.(Int,v)
        n == 106 && count > 0 && 1 <= ord <= 3 ||
            error("Unexpected geometric-character row $i")
        key = (ord,tr)
        haskey(histogram,key) && error("Duplicate geometric-character bin")
        histogram[key] = count
    end
    sum(values(histogram)) == 3 || error("Incomplete No. 106 character")
    get(histogram,(1,22),0) == 1 || error("Incorrect identity trace")
    return histogram
end

function r106_preflight()
    hashes = r106_source_hashes()
    r106_table_check(); r106_containment_check()
    expected = r106_geometric_character()
    p = r67_parent()
    r106_note("No. 67 cache, No. 106 direct edge, and exact character passed")
    r106_note("Source hashes: $hashes")
    return p,expected,hashes
end

# Every C3 subgroup of A4 is generated by one of its order-three elements.
# Enumerate all such elements and deduplicate exact subgroup element sets.
function r106_raw(ctx)
    raw = Dict{Any,Int}()
    for a in 1:12
        ctx.orders[a] == 3 || continue
        A = r67_subgroup(ctx,[a])
        length(A) == 3 && all(i <= 12 for i in A) ||
            error("Wrong C3 subgroup in the symplectic kernel")
        get!(raw,A,a)
    end
    length(raw) == 4 || error("Expected the four C3 subgroups of A4")
    return raw
end

function r106_groups(output)
    ispath(output) && error("Refusing to overwrite $output")
    endswith(lowercase(output),".mrdi") || error("Group path must end in .mrdi")
    p,expected,hashes = r106_preflight()
    ctx = r67_context(p)
    raw = r106_raw(ctx)
    classes = r67_classes(ctx,raw)
    candidates = NamedTuple[]; matches = 0
    for (class_number,c) in enumerate(classes)
        a = raw[c.key]
        @assert r67_group_id(ctx,c.key,[a]) == r106_id
        hist = r67_histogram(ctx,c.key)
        matched = hist == expected
        matches += matched
        push!(candidates,(child=106,parent=67,class_number=class_number,
            orbit_size=c.orbit_size,subgroup_indices=c.key,group_id=r106_id,
            symplectic_generator_index=a,symplectic_generator=ctx.elements[a],
            primitive_character_histogram=hist,character_match=matched))
        r106_note("No. 106 class $class_number: orbit $(c.orbit_size), character match=$matched")
    end
    matches > 0 || error("No No. 67 subgroup matches the No. 106 character")
    save(output,(format_version=1,source_hashes=hashes,
        method="all four C3 subgroups of the A4 kernel; exact closure and full parent conjugacy",
        parent_number=67,parent_group_order=36,complete_within_saved_parent=true,
        numbered_assignment_claimed=false,raw_subgroups=length(raw),
        parent_classes=length(classes),character_matches=matches,
        candidates=r67_saved_collection(candidates),lattice_and_root_checks_done=false))
    check = load(output)
    @assert check.source_hashes == hashes && length(check.candidates) == length(candidates)
    r106_note("Saved and reloaded $output")
end

function r106_restriction(p,c)
    identity = identity_matrix(QQ,22)
    result = complete_cyclic_restriction(p.parent,
        c.symplectic_generator,identity;
        child_number=106,parent_number=67,index=1,
        expected_rank_S=12,expected_dimension=8,
        expected_group_id=r106_id,verify_group_id=false,
        verify_roots=false,verify_symplectic_saturation=false)
    @assert rank(result.P_in_Lambda0) == 10
    @assert rank(result.K_in_Lambda0) == 12
    return result
end

function r106_lattices(output,groups_path)
    ispath(output) && error("Refusing to overwrite $output")
    endswith(lowercase(output),".mrdi") || error("Lattice path must end in .mrdi")
    groups = load(groups_path)
    @assert groups.format_version == 1 && groups.source_hashes == r106_source_hashes()
    p = r67_parent()
    summaries = NamedTuple[]; results = NamedTuple[]
    for c in groups.candidates
        c.character_match || continue
        T = invariant_lattice(p.L,[c.symplectic_generator];
            ambient_representation=false)
        S = orthogonal_submodule(p.L,T)
        reason = ""
        if rank(S) != 12 || rank(T) != 10
            reason = "symplectic rank mismatch"
        elseif signature_tuple(S) != (12,0,0) || signature_tuple(T) != (8,0,2)
            reason = "symplectic signature mismatch"
        end
        push!(summaries,(child=106,class_number=c.class_number,
            rank_S=rank(S),rank_T=rank(T),matched=isempty(reason),reason=reason))
        r106_note("No. 106 class $(c.class_number): S=$(rank(S)), T=$(rank(T)), reason=$reason")
        isempty(reason) || continue
        push!(results,(child=106,class_number=c.class_number,
            result=r106_restriction(p,c)))
    end
    isempty(results) && error("No character-matched No. 106 class passed lattice filters")
    save(output,(format_version=1,source_hashes=groups.source_hashes,
        groups_file_hash=r67_hash(groups_path),
        summaries=r67_saved_collection(summaries),results=Tuple(results),
        target_numbers=(106,),match_count=length(results),
        complete_lattice_pass=true,roots_verified=false,
        symplectic_saturation_verified=false,numbered_assignment_claimed=false))
    check = load(output)
    @assert check.source_hashes == groups.source_hashes
    @assert length(check.results) == length(results)
    r106_note("Saved and reloaded $output; lattice matches=$(length(results))")
end

function r106_verify(output,lattices_path,groups_path)
    ispath(output) && error("Refusing to overwrite $output")
    endswith(lowercase(output),".mrdi") || error("Verified path must end in .mrdi")
    groups,data = load(groups_path),load(lattices_path)
    @assert groups.format_version == data.format_version == 1
    @assert groups.source_hashes == data.source_hashes == r106_source_hashes()
    @assert data.groups_file_hash == r67_hash(groups_path)
    @assert data.complete_lattice_pass
    p = r67_parent(); ctx = r67_context(p)
    expected = r106_geometric_character()
    verified = NamedTuple[]; obstructed = NamedTuple[]
    for r in data.results
        c = only(x for x in groups.candidates if
            x.child == 106 && x.class_number == r.class_number)
        @assert c.character_match
        a = c.symplectic_generator_index
        A = r67_subgroup(ctx,[a])
        @assert A == c.subgroup_indices && all(i <= 12 for i in A)
        @assert r67_group_id(ctx,A,[a]) == r106_id
        @assert r67_histogram(ctx,A) == c.primitive_character_histogram == expected
        result = r106_restriction(p,c)
        @assert gram_matrix(lattice(result.S_in_Lambda0)) ==
            gram_matrix(lattice(r.result.S_in_Lambda0))
        @assert gram_matrix(lattice(result.T_in_Lambda0)) ==
            gram_matrix(lattice(r.result.T_in_Lambda0))
        @assert gram_matrix(result.P_in_Lambda0) == gram_matrix(r.result.P_in_Lambda0)
        @assert gram_matrix(result.K_in_Lambda0) == gram_matrix(r.result.K_in_Lambda0)
        @assert isometry(result.T_action) == isometry(r.result.T_action)
        if has_root(result.K_in_Lambda0,p.L)
            push!(obstructed,(child=106,parent=67,class_number=r.class_number,
                group_id=r106_id))
            r106_note("No. 106 class $(r.class_number): root obstruction")
        else
            push!(verified,(child=106,parent=67,class_number=r.class_number,
                group_id=r106_id,roots_verified=true,result=result))
            r106_note("No. 106 class $(r.class_number): subgroup, lattice and roots verified")
        end
    end
    @assert length(verified)+length(obstructed) == data.match_count
    save(output,(format_version=1,source_hashes=data.source_hashes,
        groups_file_hash=r67_hash(groups_path),
        lattices_file_hash=r67_hash(lattices_path),
        verified_results=r67_saved_collection(verified),
        root_obstructed=r67_saved_collection(obstructed),
        target_numbers=(106,),verified_count=length(verified),
        obstructed_count=length(obstructed),roots_verified=true,
        complete_lattice_pass=true,complete_within_saved_parent=true,
        symplectic_saturation_verified=false,numbered_assignment_claimed=false))
    check = load(output)
    @assert check.source_hashes == data.source_hashes
    @assert length(check.verified_results) == length(verified)
    @assert length(check.root_obstructed) == length(obstructed)
    r106_note("Saved and reloaded $output; root-free=$(length(verified)), obstructed=$(length(obstructed))")
end

function r106_main()
    isempty(ARGS) && error("Choose preflight, groups, lattices, or verify")
    stage = ARGS[1]
    if stage == "preflight"
        length(ARGS) == 1 || error("preflight takes no arguments")
        r106_preflight()
    elseif stage == "groups"
        length(ARGS) <= 2 || error("groups [output.mrdi]")
        r106_groups(length(ARGS) == 2 ? abspath(ARGS[2]) : r106_groups_file)
    elseif stage == "lattices"
        length(ARGS) <= 3 || error("lattices [output.mrdi] [groups.mrdi]")
        r106_lattices(length(ARGS) >= 2 ? abspath(ARGS[2]) : r106_lattices_file,
            length(ARGS) == 3 ? abspath(ARGS[3]) : r106_groups_file)
    elseif stage == "verify"
        length(ARGS) <= 4 || error("verify [output.mrdi] [lattices.mrdi] [groups.mrdi]")
        r106_verify(length(ARGS) >= 2 ? abspath(ARGS[2]) : r106_verified_file,
            length(ARGS) >= 3 ? abspath(ARGS[3]) : r106_lattices_file,
            length(ARGS) == 4 ? abspath(ARGS[4]) : r106_groups_file)
    else
        error("Unknown stage: $stage")
    end
end

if abspath(PROGRAM_FILE) == abspath(@__FILE__)
    r106_main()
end
