# Exhaustive C6 subgroup pilot for No. 123 inside No. 95 and No. 126 inside
# No. 50. This file does not edit the 156-row catalogue. Run `preflight`,
# `groups`, `lattices`, and `verify` in that order.
#
# The parent symplectic kernels have orders 6 and 8, respectively. In each
# parent, every target C6 subgroup is generated by a unique order-six
# element in the chosen coset f^(q/3) of its order-three quotient image.
# Parent conjugacy is computed exactly on this finite candidate set.

using SHA
include(joinpath(@__DIR__, "enumerate_restrictions_94_95_direct.jl"))
include(joinpath(@__DIR__, "restriction_functions.jl"))

const pilot123126_source = joinpath(@__DIR__, "..", "..", "oscar", "oscar_script_data.mrdi")
const pilot123126_parent95_file = joinpath(@__DIR__,
    "restriction_candidates_94_95_from_24.direct_lattices.mrdi")
const pilot123126_parent51_file = joinpath(@__DIR__, "source_51_full_lattice_group.mrdi")
const pilot123126_table = joinpath(@__DIR__, "..", "input", "family_numbering.md")
const pilot123126_containment = joinpath(@__DIR__, "..", "..", "gap_classification",
    "gap_fourfold_cross_dimension", "result", "gap_fourfold_cross_dimension_all_pairs.tsv")
const pilot123126_character = joinpath(@__DIR__,
    "restriction_next_small_geometric_characters.tsv")
const pilot123126_output = joinpath(@__DIR__,
    "restriction_pilot_123_126.groups.mrdi")
const pilot123126_lattices_file = joinpath(@__DIR__,
    "restriction_pilot_123_126.lattices.mrdi")
const pilot123126_verified_file = joinpath(@__DIR__,
    "restriction_pilot_123_126.verified.mrdi")

pilot123126_note(s) = (println(s); flush(stdout))
pilot123126_sha(path) = bytes2hex(sha256(read(path)))
pilot123126_inputs() = (pilot123126_source, pilot123126_parent95_file,
    pilot123126_parent51_file, pilot123126_table, pilot123126_containment,
    pilot123126_character)

function pilot123126_hashes()
    all(isfile, pilot123126_inputs()) || error("A required source file is missing")
    return Tuple(pilot123126_sha(path) for path in pilot123126_inputs())
end

function pilot123126_numbered_checks()
    expected = Dict(
        50 => (17, 3, 1, (24,3)),
        95 => (14, 12, 1, (72,27)),
        123 => (8, 3, 6, (6,2)),
        126 => (8, 3, 4, (6,2)),
    )
    seen = Set{Int}()
    for line in eachline(pilot123126_table)
        startswith(line, "|") || continue
        cells = strip.(split(line, '|'))
        length(cells) >= 9 || continue
        number = tryparse(Int, cells[2])
        number === nothing && continue
        haskey(expected, number) || continue
        match_id = match(r"\[(\d+),(\d+)\]", cells[8])
        match_id === nothing && error("Missing group ID in row $number")
        actual = (parse(Int,cells[3]), parse(Int,cells[6]),
            parse(Int,cells[7]),
            (parse(Int,match_id.captures[1]),parse(Int,match_id.captures[2])))
        actual == expected[number] || error("Numbered row $number changed: $actual")
        push!(seen,number)
    end
    seen == Set(keys(expected)) || error("Numbered family row missing")
end

function pilot123126_containment_checks()
    expected = Dict((123,95) => (6,1,18,216),
                    (126,50) => (4,1,18,72))
    seen = Set{Tuple{Int,Int}}()
    for (line_number,line) in enumerate(eachline(pilot123126_containment))
        line_number == 1 && continue
        fields = split(line,'\t')
        length(fields) == 12 || error("Malformed containment TSV line $line_number")
        key = (parse(Int,fields[1]),parse(Int,fields[2]))
        haskey(expected,key) || continue
        actual = Tuple(parse(Int,fields[k]) for k in 3:6)
        actual == expected[key] || error("Containment metadata changed: $key, $actual")
        fields[7:10] == ["embedded","direct","true","fail"] ||
            error("Direct strict containment not certified for $key")
        fields[12] in ("literal_matrix_subgroup","A_strict") ||
            error("Unexpected containment witness for $key")
        push!(seen,key)
    end
    seen == Set(keys(expected)) || error("A direct strict containment is missing")
end

function pilot123126_geometric_characters()
    expected = Dict(n => Dict{Tuple{Int,Int},Int}() for n in (123,126))
    for (line_number,line) in enumerate(eachline(pilot123126_character))
        if line_number == 1
            line == "family_number\tprojective_order\tprimitive_H4_trace\telement_count" ||
                error("Unexpected character TSV header")
            continue
        end
        isempty(strip(line)) && continue
        fields = split(line,'\t')
        length(fields) == 4 || error("Malformed character TSV line $line_number")
        n,ord,tr,count = parse.(Int,fields)
        haskey(expected,n) || continue
        count > 0 || error("Nonpositive character count")
        key = (ord,tr)
        haskey(expected[n],key) && error("Duplicate character bin")
        expected[n][key] = count
    end
    for n in (123,126)
        sum(values(expected[n])) == 6 || error("Incomplete character for No. $n")
        get(expected[n],(1,22),0) == 1 || error("Bad identity character for No. $n")
    end
    return expected
end

function pilot123126_fixed_rank(ctx, dimension)
    projector = sum(ctx.elements; init=zero_matrix(QQ,dimension,dimension))
    return rank(projector)
end

function pilot123126_parent95()
    cache = load(pilot123126_parent95_file)
    @assert cache.parent_number == 24 && cache.character_assignment_verified
    parent = only(r for r in cache.results if
        r.class_number == cache.assigned_class_95 && r.character_matches == [95])
    @assert parent.abstract_projective_group_id == (72,27)
    @assert parent.symplectic_intersection_id == (6,1)
    @assert parent.order == 12 && parent.dimension == 1
    L = lattice(parent.Lambda0)
    T = lattice(parent.T_in_Lambda0)
    @assert rank(L) == 22 && rank(T) == 8
    @assert rank(lattice(parent.S_in_Lambda0)) == 14
    @assert signature_tuple(L) == (20,0,2) && abs(det(gram_matrix(L))) == 3
    generators = parent.symplectic_generators_in_parent
    f = parent.extra_generator_in_parent
    @assert length(generators) == 2 && f == isometry(parent.Lambda0)
    t_embedding = basis_matrix(T)*inv(basis_matrix(L))
    @assert all(t_embedding*g == t_embedding for g in generators)
    @assert order_of_isometry(parent.T_action) == 12
    ctx = direct_context(generators,f,6,12)
    @assert sort(ctx.orders) == [1,2,2,2,3,3]
    @assert pilot123126_fixed_rank(ctx,22) == 8
    return (number=95,child=123,rank_S=8,dimension=6,index=3,
        kernel_order=6,quotient_order=12,parent=parent,L=L,T=T,f=f,ctx=ctx)
end

function pilot123126_integral_unimodular(C, dimension)
    nrows(C) == ncols(C) == dimension || return false
    all(denominator(C[i,j]) == 1 for i in 1:dimension, j in 1:dimension) &&
        abs(det(C)) == 1
end

function pilot123126_parent50()
    source = load(pilot123126_source)
    @assert source.format_version == 3 && source.completed_cases == 29
    case = source.cases[21]
    @assert case.case_index == 21
    parent = case.results[2]
    @assert parent.group_gap_id == (24,3)
    @assert parent.order == 3 && parent.dimension == 1
    L = lattice(parent.Lambda0)
    S = lattice(parent.S_in_Lambda0)
    T = lattice(parent.T_in_Lambda0)
    @assert rank(L) == 22 && rank(S) == 17 && rank(T) == 5
    @assert signature_tuple(L) == (20,0,2) && abs(det(gram_matrix(L))) == 3
    @assert order_of_isometry(parent.T_action) == 3

    cache = load(pilot123126_parent51_file)
    @assert cache.parent_number == 51 && cache.full_group_id == (32,11)
    L51 = lattice(cache.Lambda0)
    S51 = lattice(cache.S_in_Lambda0)
    @assert rank(L51) == 22 && rank(S51) == 17
    # These two primitive extensions need not use the same ambient quadratic
    # space or the same gluing. Only their common abstract S is transported.
    # Since the saved generators belong to the stable kernel on S, each one
    # extends to either primitive extension by the identity on T.
    gram_matrix(S) == gram_matrix(S51) ||
        error("No. 50 and No. 51 S bases are not the same integral lattice basis")
    @assert rank(lattice(source.cases[21].results[3].T_in_Lambda0)) == 5
    embedding_S51 = basis_matrix(S51)*inv(basis_matrix(L51))
    @assert rank(embedding_S51) == 17
    right_inverse_S51 = transpose(embedding_S51)*
        inv(embedding_S51*transpose(embedding_S51))
    @assert embedding_S51*right_inverse_S51 == identity_matrix(QQ,17)
    embedding_S = basis_matrix(S)*inv(basis_matrix(L))
    embedding_T = basis_matrix(T)*inv(basis_matrix(L))
    generators = typeof(isometry(parent.Lambda0))[]
    for g51 in cache.symplectic_generators
        # Solve gS*embedding_S51 = embedding_S51*g51 exactly. The right
        # inverse only extracts a known restriction; equality is rechecked.
        gS = embedding_S51*g51*right_inverse_S51
        @assert gS*embedding_S51 == embedding_S51*g51
        pilot123126_integral_unimodular(gS,17) ||
            error("A cached Q8 generator does not restrict integrally to S")
        S_isom = integer_lattice_with_isometry(S,gS;
            ambient_representation=false,check=true)
        @assert trivial_action_on_discriminant(S_isom)
        L_isom = integer_lattice_with_isometry(L,ambient_isometry(S_isom);
            ambient_representation=true,check=true)
        @assert trivial_action_on_discriminant(L_isom)
        g50 = isometry(L_isom)
        pilot123126_integral_unimodular(g50,22) ||
            error("A transported Q8 generator does not extend integrally to No. 50")
        @assert embedding_T*g50 == embedding_T
        @assert gS*embedding_S == embedding_S*g50
        push!(generators,g50)
    end
    f = isometry(parent.Lambda0)
    @assert all(denominator(f[i,j]) == 1 for i in 1:22, j in 1:22)
    @assert trivial_action_on_discriminant(parent.Lambda0)
    @assert length(generators) >= 2
    @assert all(embedding_T*g == embedding_T for g in generators)
    ctx = direct_context(generators,f,8,3)
    @assert sort(ctx.orders) == [1,2,4,4,4,4,4,4]
    @assert pilot123126_fixed_rank(ctx,22) == 5
    full_group = matrix_group(vcat(generators,[f]))
    @assert Int(order(full_group)) == 24
    @assert small_group_identification(full_group) == (24,3)
    return (number=50,child=126,rank_S=8,dimension=4,index=3,
        kernel_order=8,quotient_order=3,parent=parent,L=L,T=T,f=f,ctx=ctx,
        stable_S_transport_verified=true,
        transported_symplectic_generators=Tuple(generators))
end

function pilot123126_phi_power(ctx,n,k)
    for _ in 1:k
        n = ctx.phi[n]
    end
    return n
end

function pilot123126_histogram(b)
    one_L = identity_matrix(QQ,22)
    power = one_L
    result = Dict{Tuple{Int,Int},Int}()
    for k in 0:5
        ord = k == 0 ? 1 : div(6,gcd(6,k))
        tr = sum(power[i,i] for i in 1:22)
        denominator(tr) == 1 || error("Nonintegral primitive trace")
        key = (ord,Int(numerator(tr)))
        result[key] = get(result,key,0)+1
        power *= b
    end
    power == one_L || error("Expected a C6 action")
    @assert sum(values(result)) == 6 && get(result,(1,22),0) == 1
    return result
end

function pilot123126_classes(data)
    ctx, f = data.ctx, data.f
    k = div(data.quotient_order,3)
    @assert 3*k == data.quotient_order
    one_L = identity_matrix(QQ,22)
    f_to_k = f^k
    candidates = Set{Int}()
    for n in eachindex(ctx.elements)
        b = ctx.elements[n]*f_to_k
        b^6 == one_L || continue
        b^3 != one_L || continue
        sym_index = get(ctx.positions,direct_matrix_key(b^3),0)
        sym_index != 0 || error("An order-two cube left the symplectic kernel")
        @assert ctx.orders[sym_index] == 2
        push!(candidates,n)
    end
    isempty(candidates) && error("No target C6 subgroup in No. $(data.number)")
    unseen = copy(candidates)
    classes = NamedTuple[]
    while !isempty(unseen)
        first_n = minimum(unseen)
        orbit = Set([first_n])
        queue = [first_n]
        head = 1
        while head <= length(queue)
            n = queue[head]
            neighbours = [ctx.phi[n]]
            for g in ctx.generator_ids
                other = ctx.mul(ctx.mul(g,n),
                    pilot123126_phi_power(ctx,ctx.inverses[g],k))
                push!(neighbours,other)
            end
            for other in neighbours
                other in candidates || error("Order-six candidate set not conjugacy stable")
                if !(other in orbit)
                    push!(orbit,other)
                    push!(queue,other)
                end
            end
            head += 1
        end
        setdiff!(unseen,orbit)
        push!(classes,(kernel_element_index=minimum(orbit),
            parent_conjugacy_orbit_size=length(orbit)))
    end
    @assert sum(c.parent_conjugacy_orbit_size for c in classes) == length(candidates)
    return length(candidates),classes
end

function pilot123126_preflight()
    hashes = pilot123126_hashes()
    pilot123126_numbered_checks()
    pilot123126_containment_checks()
    expected = pilot123126_geometric_characters()
    parent95 = pilot123126_parent95()
    pilot123126_note("No. 95 passed: S3 kernel, C12 quotient, rank(T)=8")
    parent50 = pilot123126_parent50()
    pilot123126_note("No. 50 passed: transported Q8 kernel, C3 quotient, rank(T)=5")
    pilot123126_note("Target geometric character bins: " * string(expected))
    pilot123126_note("Source SHA-256 tuple: " * string(hashes))
    return (parent95,parent50),expected,hashes
end

function pilot123126_groups(output)
    ispath(output) && error("Refusing to overwrite $output")
    parents,expected,hashes = pilot123126_preflight()
    results = NamedTuple[]
    summaries = NamedTuple[]
    for data in parents
        raw_count,classes = pilot123126_classes(data)
        target_matches = 0
        pilot123126_note("No. $(data.child) in No. $(data.number): $raw_count order-six elements, $(length(classes)) parent conjugacy classes")
        for (class_number,cl) in enumerate(classes)
            b = data.ctx.elements[cl.kernel_element_index]*
                data.f^div(data.quotient_order,3)
            sym = b^3
            histogram = pilot123126_histogram(b)
            matched = histogram == expected[data.child]
            target_matches += matched
            push!(results,(child=data.child,parent=data.number,
                class_number=class_number,
                parent_conjugacy_orbit_size=cl.parent_conjugacy_orbit_size,
                kernel_element_index=cl.kernel_element_index,
                quotient_coset_power=div(data.quotient_order,3),
                geometric_character_match=matched,
                primitive_character_histogram=histogram,
                symplectic_generator=sym,extra_generator=b))
            pilot123126_note("  class $class_number: orbit $(cl.parent_conjugacy_orbit_size), geometric character match=$matched")
        end
        target_matches > 0 || error("No class matches No. $(data.child) character")
        push!(summaries,(child=data.child,parent=data.number,
            raw_order_six_elements=raw_count,
            parent_conjugacy_classes=length(classes),
            geometric_character_matches=target_matches))
    end
    save(output,(format_version=1,
        method="all order-six n*f^(q/3), modulo conjugacy by the full parent",
        source_hashes=hashes,
        parent50_stable_S_transport_verified=true,
        summaries=Tuple(summaries),results=Tuple(results),
        lattice_and_root_checks_done=false,
        numbered_assignment_claimed=false))
    check = load(output)
    @assert check.format_version == 1 && check.source_hashes == hashes
    @assert length(check.results) == length(results)
    pilot123126_note("Saved and reloaded $output")
end

function pilot123126_lattices(output, groups_path)
    ispath(output) && error("Refusing to overwrite $output")
    groups = load(groups_path)
    @assert groups.format_version == 1
    @assert groups.source_hashes == pilot123126_hashes()
    @assert groups.parent50_stable_S_transport_verified
    parents = Dict(123 => pilot123126_parent95(),
                   126 => pilot123126_parent50())
    results = NamedTuple[]
    for candidate in groups.results
        candidate.geometric_character_match || continue
        data = parents[candidate.child]
        @assert data.number == candidate.parent
        @assert candidate.primitive_character_histogram ==
            pilot123126_geometric_characters()[candidate.child]
        # This constructs the complete embedded S/T/P/K and full-rank T
        # action, checking the quotient order and period dimension. Group
        # and root checks are kept for the independent verify stage.
        result = complete_cyclic_restriction(data.parent,
            candidate.symplectic_generator,candidate.extra_generator;
            child_number=data.child,parent_number=data.number,
            index=data.index,expected_rank_S=data.rank_S,
            expected_dimension=data.dimension,expected_group_id=(6,2),
            verify_group_id=false,verify_roots=false,
            verify_symplectic_saturation=false)
        @assert rank(lattice(result.S_in_Lambda0)) == 8
        @assert rank(lattice(result.T_in_Lambda0)) == 14
        @assert Int(order_of_isometry(result.T_action)) == 3
        push!(results,(child=data.child,parent=data.number,
            class_number=candidate.class_number,result=result))
        pilot123126_note("No. $(data.child) class $(candidate.class_number): " *
            "rank(S)=8, rank(P)=$(rank(result.P_in_Lambda0)), " *
            "rank(K)=$(rank(result.K_in_Lambda0)), dimension=$(result.dimension)")
    end
    matches = Tuple((child=n,count=count(r -> r.child == n,results))
        for n in (123,126))
    @assert all(m.count > 0 for m in matches)
    save(output,(format_version=1,source_hashes=groups.source_hashes,
        groups_file_hash=pilot123126_sha(groups_path),
        results=Tuple(results),matching_parent_match_counts=matches,
        roots_verified=false,extracted_group_verified=false,
        symplectic_saturation_verified=false))
    reloaded = load(output)
    @assert reloaded.source_hashes == groups.source_hashes
    @assert length(reloaded.results) == length(results)
    pilot123126_note("Saved and reloaded $output; lattice matches: $matches")
end

function pilot123126_verify(output, lattices_path, groups_path)
    ispath(output) && error("Refusing to overwrite $output")
    groups = load(groups_path)
    data = load(lattices_path)
    @assert groups.format_version == data.format_version == 1
    @assert groups.source_hashes == data.source_hashes == pilot123126_hashes()
    @assert data.groups_file_hash == pilot123126_sha(groups_path)
    parents = Dict(123 => pilot123126_parent95(),
                   126 => pilot123126_parent50())
    verified = NamedTuple[]
    for r in data.results
        candidate = only(c for c in groups.results if
            c.child == r.child && c.parent == r.parent &&
            c.class_number == r.class_number)
        @assert candidate.geometric_character_match
        parent = parents[r.child]
        @assert parent.number == r.parent
        b = candidate.extra_generator
        @assert b^3 == candidate.symplectic_generator
        identity_22 = identity_matrix(QQ,22)
        @assert b^6 == identity_22 && b^3 != identity_22 &&
                b^2 != identity_22
        # The exact matrix order is six, hence <b> is cyclic [6,2].
        @assert pilot123126_histogram(b) ==
            candidate.primitive_character_histogram
        result = complete_cyclic_restriction(parent.parent,
            candidate.symplectic_generator,b;
            child_number=parent.child,parent_number=parent.number,
            index=parent.index,expected_rank_S=parent.rank_S,
            expected_dimension=parent.dimension,expected_group_id=(6,2),
            verify_group_id=false,verify_roots=true,
            verify_symplectic_saturation=false)
        @assert gram_matrix(lattice(result.S_in_Lambda0)) ==
            gram_matrix(lattice(r.result.S_in_Lambda0))
        @assert gram_matrix(lattice(result.T_in_Lambda0)) ==
            gram_matrix(lattice(r.result.T_in_Lambda0))
        @assert gram_matrix(result.P_in_Lambda0) ==
            gram_matrix(r.result.P_in_Lambda0)
        @assert gram_matrix(result.K_in_Lambda0) ==
            gram_matrix(r.result.K_in_Lambda0)
        @assert isometry(result.T_action) == isometry(r.result.T_action)
        push!(verified,(child=r.child,parent=r.parent,
            class_number=r.class_number,group_id=(6,2),
            extracted_group_verified=true,roots_verified=true,
            result=result))
        pilot123126_note("No. $(r.child) class $(r.class_number): " *
            "C6 group and root obstruction verified")
    end
    matches = Tuple((child=n,count=count(r -> r.child == n,verified))
        for n in (123,126))
    @assert matches == data.matching_parent_match_counts
    save(output,(format_version=1,source_hashes=data.source_hashes,
        groups_file_hash=pilot123126_sha(groups_path),
        lattices_file_hash=pilot123126_sha(lattices_path),
        verified_results=Tuple(verified),matching_parent_match_counts=matches,
        roots_verified=true,extracted_group_verified=true,
        symplectic_saturation_verified=false))
    reloaded = load(output)
    @assert reloaded.source_hashes == data.source_hashes
    @assert length(reloaded.verified_results) == length(verified)
    pilot123126_note("Saved and reloaded $output; verified matches: $matches")
end

function pilot123126_main()
    length(ARGS) in 1:4 || error("Use preflight, groups, lattices, or verify")
    if ARGS[1] == "preflight"
        length(ARGS) == 1 || error("preflight takes no output argument")
        pilot123126_preflight()
    elseif ARGS[1] == "groups"
        length(ARGS) <= 2 || error("groups [output.mrdi]")
        pilot123126_groups(length(ARGS) == 2 ? abspath(ARGS[2]) : pilot123126_output)
    elseif ARGS[1] == "lattices"
        length(ARGS) <= 3 || error("lattices [output.mrdi] [groups.mrdi]")
        pilot123126_lattices(length(ARGS) >= 2 ? abspath(ARGS[2]) :
            pilot123126_lattices_file,
            length(ARGS) == 3 ? abspath(ARGS[3]) : pilot123126_output)
    elseif ARGS[1] == "verify"
        length(ARGS) <= 4 || error("verify [output.mrdi] [lattices.mrdi] [groups.mrdi]")
        pilot123126_verify(length(ARGS) >= 2 ? abspath(ARGS[2]) :
            pilot123126_verified_file,
            length(ARGS) >= 3 ? abspath(ARGS[3]) : pilot123126_lattices_file,
            length(ARGS) == 4 ? abspath(ARGS[4]) : pilot123126_output)
    else
        error("Unknown stage: $(ARGS[1])")
    end
end

pilot123126_main()
