#############################################################################
## Build the filtered small non-abelian input used by saturation.
##
## This is a data-selection step only.  It does not repeat representation
## enumeration, the Gonzalez--Aguilera--Liendo restriction, or a smoothness
## calculation. The generated data file retains the 46 smooth and seven
## unresolved records and omits the 129 certified singular records.
#############################################################################

CF_SAT_PrepareSmallPathData := function()
    if IsExistingFile("../gap_small_nonabelian/gap_small_nonabelian_data.g") then
        return rec(
            sourceDirectory := "../gap_small_nonabelian/",
            smoothnessDirectory := "../gap_smoothness/",
            outputFile := "gap_small_nonabelian_saturation_data.g"
        );
    fi;

    if IsExistingFile(
        "gap_classification/gap_small_nonabelian/gap_small_nonabelian_data.g"
    ) then
        return rec(
            sourceDirectory := "gap_classification/gap_small_nonabelian/",
            smoothnessDirectory := "gap_classification/gap_smoothness/",
            outputFile := Concatenation(
                "gap_classification/gap_saturation/",
                "gap_small_nonabelian_saturation_data.g"
            )
        );
    fi;

    Error("Run from the repository root or gap_classification/gap_saturation.");
end;

CF_SAT_PrepareSmallPathRecord := CF_SAT_PrepareSmallPathData();
CF_SAT_PrepareSmallCandidateFile := Concatenation(
    CF_SAT_PrepareSmallPathRecord.sourceDirectory,
    "gap_small_nonabelian_data.g"
);
CF_SAT_PrepareSmallSmoothnessFile := Concatenation(
    CF_SAT_PrepareSmallPathRecord.smoothnessDirectory,
    "gap_small_nonabelian_smoothness.out"
);

Read(CF_SAT_PrepareSmallCandidateFile);
Read(CF_SAT_PrepareSmallSmoothnessFile);

CF_SAT_PrepareSmallSymplecticDimension := function(symplecticPart)
    if symplecticPart = "C3" or symplecticPart = "C2^2" then
        return 8;
    elif symplecticPart = "C4" or symplecticPart = "S3" then
        return 6;
    fi;
    Error("Unexpected small symplectic part: ", symplecticPart, ".");
end;

CF_SAT_PrepareSmallInput := function()
    local selected, result,
          candidate, copy, smoothCount, unresolvedCount, singularCount;

    selected := [];
    smoothCount := 0;
    unresolvedCount := 0;
    singularCount := 0;

    for result in SmallNonabelianSmoothnessResults do
        if result.status = "singular" then
            singularCount := singularCount + 1;
        elif result.status = "smooth" or result.status = "unknown" then
            candidate := First(
                SmallNonabelianCandidates,
                r -> r.candidateNumber = result.candidateNumber
            );
            if candidate = fail then
                Error(
                    "Missing candidate ", result.candidateNumber,
                    " from the smoothness output."
                );
            fi;

            copy := ShallowCopy(candidate);
            copy.smoothnessStatus := result.status;
            copy.smoothnessProofType := result.proofType;
            copy.requiresSmoothnessProof := result.status = "unknown";
            copy.eligibleForSaturation := true;
            copy.isSymplecticFamily :=
                copy.expectedModuliDimension
                = CF_SAT_PrepareSmallSymplecticDimension(
                    copy.symplecticPart
                )
                and copy.determinantImageOrder = copy.genericIndex;

            # The source enumeration number is needed only to match the two
            # input files above.  It is not part of the curated saturation
            # data or any later family identifier.
            Unbind(copy.candidateNumber);

            if result.status = "smooth" then
                smoothCount := smoothCount + 1;
                copy.smoothnessCoefficients := result.guessedCoefficients;
                copy.smoothPolynomial := result.smoothPolynomial;
            else
                unresolvedCount := unresolvedCount + 1;
            fi;

            Add(selected, copy);
        else
            Error("Unexpected smoothness status: ", result.status, ".");
        fi;
    od;

    if smoothCount <> 46 or unresolvedCount <> 7 or singularCount <> 129 then
        Error(
            "Unexpected selection totals: smooth=", smoothCount,
            ", unknown=", unresolvedCount,
            ", singular=", singularCount, "."
        );
    fi;

    PrintTo(
        CF_SAT_PrepareSmallPathRecord.outputFile,
        "# Generated by gap_prepare_small_nonabelian_input.g.\n",
        "# Only smooth and unresolved candidates are stored.\n\n",
        "SmallNonabelianSaturationSourceRecord := rec(\n",
        "  candidateDataFile := \"gap_small_nonabelian_data.g\",\n",
        "  smoothnessOutputFile := \"gap_small_nonabelian_smoothness.out\",\n",
        "  smoothCount := 46,\n",
        "  unresolvedCount := 7,\n",
        "  excludedSingularCount := 129 );\n\n",
        "SmallNonabelianSaturationCandidates := ", selected, ";\n\n",
        "SmallNonabelianSaturationSmoothCandidates := Filtered(\n",
        "  SmallNonabelianSaturationCandidates,\n",
        "  r -> r.smoothnessStatus = \"smooth\" );\n",
        "SmallNonabelianSaturationUnresolvedCandidates := Filtered(\n",
        "  SmallNonabelianSaturationCandidates,\n",
        "  r -> r.smoothnessStatus = \"unknown\" );\n"
    );

    return rec(
        outputFile := CF_SAT_PrepareSmallPathRecord.outputFile,
        smoothCount := smoothCount,
        unresolvedCount := unresolvedCount,
        excludedSingularCount := singularCount
    );
end;

CF_SAT_SmallPreparationResult := CF_SAT_PrepareSmallInput();
