"""Exact integral index-three H^4 extension from the saved L and plane vector.

The rank-23 basis is (Pi, L-basis), where Pi=(h^2+p)/3 and p is the saved
norm-24 projection. All matrices use the repository's row-action convention.
This does not enumerate other gluings or prove geometric realizability.
"""

from hashlib import sha256
from json import loads
from pathlib import Path

from alternative_family_127_g13_full_l_audit import (
    SOURCE, block, determinant, eye, inertia, mul, pair, transpose,
)


OUT = Path(__file__).resolve().parent / "alternative_family_127_g13_h4_plane_audit.out"
INPUT_SHA = "43f385e222bda664e485d88ea3a8c83981793e4f2fbda2be8df184c29d886567"


def check():
    raw = SOURCE.read_bytes()
    assert sha256(raw).hexdigest() == INPUT_SHA
    data = loads(raw)
    assert data["family"] == 127 and data["search_complete"] is False
    w = data["first_witness"]
    gl, g, s, p = w["gram"], w["g"], w["s"], w["plane"]
    assert len(gl) == len(g) == len(s) == len(p) == 22
    assert determinant(gl) == 3 and inertia(gl) == (20, 2)
    assert pair(p, p, gl) == 24
    assert mul([p], g) == [p] and mul([p], s) == [p]
    p_pair = mul([p], gl)[0]
    assert all(x % 3 == 0 for x in p_pair)
    cross = [x // 3 for x in p_pair]

    # H is generated by the projected plane class Pi and the entire L.
    gh = [[3] + cross]
    gh += [[cross[i]] + gl[i] for i in range(22)]
    assert gh == transpose(gh)
    assert determinant(gh) == 1
    assert inertia(gh) == (21, 2)
    assert gh[0][0] == 3 and all(gh[i][i] % 2 == 0 for i in range(1, 23))

    h2 = [3] + [-x for x in p]  # h^2 = 3 Pi - p.
    pi = [1] + [0] * 22
    assert pair(h2, h2, gh) == 3
    assert pair(pi, pi, gh) == 3 and pair(h2, pi, gh) == 1
    assert mul([h2], gh)[0] == [1] + [0] * 22
    # Characteristic h^2: x^2 == x.h^2 mod 2 on a full integral basis.
    assert all((gh[i][i] - mul([h2], gh)[0][i]) % 2 == 0 for i in range(23))
    assert (3 * pi[0] - h2[0] == 0) and [-x for x in h2[1:]] == p

    embed = [h2] + [[0] + row for row in eye(22)]
    assert determinant(embed) == 3
    assert mul(mul(embed, gh), transpose(embed)) == block([[3]], gl)

    gh_g = block([[1]], g)
    gh_s = block([[1]], s)
    ident = eye(23)
    assert mul(mul(gh_g, gh), transpose(gh_g)) == gh
    assert mul(mul(gh_s, gh), transpose(gh_s)) == gh
    assert mul(gh_g, gh_g) != ident and mul(mul(gh_g, gh_g), mul(gh_g, gh_g)) == ident
    assert mul(gh_s, gh_s) == ident and mul(gh_g, gh_s) == mul(gh_s, gh_g)
    assert mul([h2], gh_g) == [h2] and mul([h2], gh_s) == [h2]
    assert mul([pi], gh_g) == [pi] and mul([pi], gh_s) == [pi]

    return [
        f"source_sha256={INPUT_SHA}",
        "H4=Z.Pi+L, index[H4:<h2>+L]=3; Gram rank23 determinant1 signature(21,2) odd",
        "h2=3Pi-p primitive characteristic, norm3, h2 perp L",
        "Pi=(h2+p)/3 fixed by g,s; norm3 and degree h2.Pi=1",
        "g,s extend as integral commuting isometries of H4 fixing h2 and Pi",
        "RESULT=PASS; one saved witness only, no monodromy/geometric sufficiency claim",
    ]


if __name__ == "__main__":
    assert not OUT.exists(), f"Refusing to overwrite {OUT}"
    lines = check()
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))
