# Exact geometric input for the six low-rank action-maximal cases whose
# integral lattice actions are not contained in the recorded rank >= 15 run.
#
# Convention: a diagonal generator with modulus m and exponents a acts by
# x_i |-> zeta_m^a_i x_i and fixes every cubic in the displayed invariant
# space.  Scalar cubic roots of unity are included only in the strict lift.

const maximal_family_data = [
    (
        number = 96,
        symplectic_group = "S3",
        projective_group = "S3 x C24",
        projective_group_id = (144, 69),
        strict_linear_group_id = (432, 464),
        rank_S = 14,
        rank_T = 8,
        generic_index = 2,
        full_index = 24,
        family_dimension = 0,
        invariant_dimension = 5,
        centralizer_dimension = 5,
        coordinate_model = "readable S3 coordinates",
        diagonal_modulus = 24,
        diagonal_exponents = [3, 18, 12, 0, 8, 0],
        other_generators = ["swap x5 and x6", "zeta3 * I6 (strict lift only)"],
        determinant_exponent = 17,
        invariant_basis = [
            "x1^2*x2",
            "x2^2*x3",
            "x3^2*x4",
            "x4^3",
            "x5^3 + x6^3",
        ],
        representative_equation =
            "x1^2*x2 + x2^2*x3 + x3^2*x4 + x4^3 + x5^3 + x6^3",
        expected_full_character = Dict(3 => 1, 6 => 2, 24 => 2),
        expected_T_character = Dict(24 => 1),
        expected_S_character = Dict(3 => 1, 6 => 2, 24 => 1),
        signature_blocks = [
            (location = "S", cyclotomic = 3, multiplicity = 1, signature = (2, 0)),
            (location = "S", cyclotomic = 6, multiplicity = 2, signature = (4, 0)),
            (location = "S", cyclotomic = 24, multiplicity = 1, signature = (8, 0)),
            (location = "T", cyclotomic = 24, multiplicity = 1, signature = (6, 2)),
        ],
        source =
            "gap_classification/gap_small_nonabelian/gap_small_nonabelian_s3.g",
    ),
    (
        number = 127,
        symplectic_group = "C2",
        projective_group = "C4 x C2",
        projective_group_id = (8, 2),
        strict_linear_group_id = (24, 9),
        rank_S = 8,
        rank_T = 14,
        generic_index = 1,
        full_index = 4,
        family_dimension = 4,
        invariant_dimension = 12,
        centralizer_dimension = 8,
        coordinate_model = "standard C2 coordinates",
        diagonal_modulus = 4,
        diagonal_exponents = [1, 2, 0, 0, 0, 2],
        symplectic_involution_exponents = [0, 0, 0, 0, 1, 1],
        other_generators = [
            "diag(1,1,1,1,-1,-1)",
            "zeta3 * I6 (strict lift only)",
        ],
        determinant_exponent = 1,
        # These are indices in the local C2 basis P_1,...,P_32.
        invariant_basis_indices = [2, 15, 16, 21, 23, 24, 25, 26, 28, 29, 30, 32],
        invariant_basis = [
            "x1^2*x2",
            "x2^2*x3",
            "x2^2*x4",
            "x2*x5*x6",
            "x3^3",
            "x3^2*x4",
            "x3*x4^2",
            "x3*x5^2",
            "x3*x6^2",
            "x4^3",
            "x4*x5^2",
            "x4*x6^2",
        ],
        representative_equation = nothing,
        expected_full_character = Dict(1 => 2, 2 => 4, 4 => 8),
        expected_T_character = Dict(1 => 1, 2 => 3, 4 => 5),
        expected_S_character = Dict(1 => 1, 2 => 1, 4 => 3),
        signature_blocks = [
            (location = "S", cyclotomic = 1, multiplicity = 1, signature = (1, 0)),
            (location = "S", cyclotomic = 2, multiplicity = 1, signature = (1, 0)),
            (location = "S", cyclotomic = 4, multiplicity = 3, signature = (6, 0)),
            (location = "T", cyclotomic = 1, multiplicity = 1, signature = (1, 0)),
            (location = "T", cyclotomic = 2, multiplicity = 3, signature = (3, 0)),
            (location = "T", cyclotomic = 4, multiplicity = 5, signature = (8, 2)),
        ],
        source =
            "remark/input/family_generators.g, family 127",
    ),
    (
        number = 152,
        symplectic_group = "1",
        projective_group = "C16 (family 2)",
        projective_group_id = (16, 1),
        strict_linear_group_id = (48, 2),
        rank_S = 0,
        rank_T = 22,
        generic_index = 1,
        full_index = 16,
        family_dimension = 1,
        invariant_dimension = 7,
        centralizer_dimension = 6,
        coordinate_model = "canonical coordinates",
        diagonal_modulus = 16,
        diagonal_exponents = [1, 14, 4, 12, 8, 0],
        other_generators = ["zeta3 * I6 (strict lift only)"],
        determinant_exponent = 7,
        invariant_basis_indices = [2, 23, 39, 43, 48, 54, 56],
        invariant_basis = [
            "x1^2*x2",
            "x2^2*x3",
            "x3^2*x5",
            "x3*x4*x6",
            "x4^2*x5",
            "x5^2*x6",
            "x6^3",
        ],
        representative_equation = nothing,
        expected_full_character = Dict(1 => 2, 2 => 2, 4 => 1, 16 => 2),
        expected_T_character = Dict(1 => 2, 2 => 2, 4 => 1, 16 => 2),
        expected_S_character = Dict{Int, Int}(),
        signature_blocks = [
            (location = "T", cyclotomic = 1, multiplicity = 2, signature = (2, 0)),
            (location = "T", cyclotomic = 2, multiplicity = 2, signature = (2, 0)),
            (location = "T", cyclotomic = 4, multiplicity = 1, signature = (2, 0)),
            (location = "T", cyclotomic = 16, multiplicity = 2, signature = (14, 2)),
        ],
        source =
            "remark/input/family_generators.g, family 152",
    ),
    (
        number = 154,
        symplectic_group = "1",
        projective_group = "C24 (family 2)",
        projective_group_id = (24, 2),
        strict_linear_group_id = (72, 14),
        rank_S = 0,
        rank_T = 22,
        generic_index = 1,
        full_index = 24,
        family_dimension = 1,
        invariant_dimension = 7,
        centralizer_dimension = 6,
        coordinate_model = "canonical coordinates",
        diagonal_modulus = 24,
        diagonal_exponents = [15, 18, 6, 12, 0, 16],
        other_generators = ["zeta3 * I6 (strict lift only)"],
        determinant_exponent = 19,
        invariant_basis_indices = [2, 24, 29, 38, 48, 53, 56],
        invariant_basis = [
            "x1^2*x2",
            "x2^2*x4",
            "x2*x3*x5",
            "x3^2*x4",
            "x4^2*x5",
            "x5^3",
            "x6^3",
        ],
        representative_equation = nothing,
        expected_full_character = Dict(3 => 1, 12 => 1, 24 => 2),
        expected_T_character = Dict(3 => 1, 12 => 1, 24 => 2),
        expected_S_character = Dict{Int, Int}(),
        signature_blocks = [
            (location = "T", cyclotomic = 3, multiplicity = 1, signature = (2, 0)),
            (location = "T", cyclotomic = 12, multiplicity = 1, signature = (4, 0)),
            (location = "T", cyclotomic = 24, multiplicity = 2, signature = (14, 2)),
        ],
        source =
            "remark/input/family_generators.g, family 154",
    ),
    (
        number = 155,
        symplectic_group = "1",
        projective_group = "C32",
        projective_group_id = (32, 1),
        strict_linear_group_id = (96, 2),
        rank_S = 0,
        rank_T = 22,
        generic_index = 1,
        full_index = 32,
        family_dimension = 0,
        invariant_dimension = 6,
        centralizer_dimension = 6,
        coordinate_model = "canonical coordinates",
        diagonal_modulus = 32,
        diagonal_exponents = [1, 30, 4, 24, 16, 0],
        other_generators = ["zeta3 * I6 (strict lift only)"],
        determinant_exponent = 11,
        invariant_basis_indices = [2, 23, 38, 48, 54, 56],
        invariant_basis = [
            "x1^2*x2",
            "x2^2*x3",
            "x3^2*x4",
            "x4^2*x5",
            "x5^2*x6",
            "x6^3",
        ],
        representative_equation =
            "x1^2*x2 + x2^2*x3 + x3^2*x4 + x4^2*x5 + x5^2*x6 + x6^3",
        expected_full_character = Dict(1 => 1, 2 => 1, 8 => 1, 32 => 1),
        expected_T_character = Dict(1 => 1, 2 => 1, 8 => 1, 32 => 1),
        expected_S_character = Dict{Int, Int}(),
        signature_blocks = [
            (location = "T", cyclotomic = 1, multiplicity = 1, signature = (1, 0)),
            (location = "T", cyclotomic = 2, multiplicity = 1, signature = (1, 0)),
            (location = "T", cyclotomic = 8, multiplicity = 1, signature = (4, 0)),
            (location = "T", cyclotomic = 32, multiplicity = 1, signature = (14, 2)),
        ],
        source =
            "gap_classification/gap_liftable_abelian/gap_liftable_abelian_data.g",
    ),
    (
        number = 156,
        symplectic_group = "1",
        projective_group = "C48",
        projective_group_id = (48, 2),
        strict_linear_group_id = (144, 30),
        rank_S = 0,
        rank_T = 22,
        generic_index = 1,
        full_index = 48,
        family_dimension = 0,
        invariant_dimension = 6,
        centralizer_dimension = 6,
        coordinate_model = "canonical coordinates",
        diagonal_modulus = 48,
        diagonal_exponents = [3, 42, 12, 24, 0, 16],
        other_generators = ["zeta3 * I6 (strict lift only)"],
        determinant_exponent = 1,
        invariant_basis_indices = [2, 23, 38, 48, 53, 56],
        invariant_basis = [
            "x1^2*x2",
            "x2^2*x3",
            "x3^2*x4",
            "x4^2*x5",
            "x5^3",
            "x6^3",
        ],
        representative_equation =
            "x1^2*x2 + x2^2*x3 + x3^2*x4 + x4^2*x5 + x5^3 + x6^3",
        expected_full_character = Dict(3 => 1, 12 => 1, 48 => 1),
        expected_T_character = Dict(3 => 1, 12 => 1, 48 => 1),
        expected_S_character = Dict{Int, Int}(),
        signature_blocks = [
            (location = "T", cyclotomic = 3, multiplicity = 1, signature = (2, 0)),
            (location = "T", cyclotomic = 12, multiplicity = 1, signature = (4, 0)),
            (location = "T", cyclotomic = 48, multiplicity = 1, signature = (14, 2)),
        ],
        source =
            "gap_classification/gap_liftable_abelian/gap_liftable_abelian_data.g",
    ),
]
