#############################################################################
##
##  gap_yyz_bounds.g
##
##  GAP-assisted calculation of the group-theoretic YYZ bounds for the
##  non-symplectic index of a smooth cubic fourfold.
##
##  Related preprint:
##    Jie Fu, Shihao Wang, Zhiwei Zheng,
##    "Non-Symplectic Indices of Automorphism Groups of Smooth Cubic
##    Fourfolds", arXiv:2606.11754v1 [math.AG], 10 June 2026.
##
##  Mathematical input:
##    - the 34 symplectic automorphism groups classified by Laza-Zheng;
##    - the 15 maximal groups acting faithfully on smooth cubic fourfolds
##      classified by Yang-Yu-Zhu;
##    - the restriction that an admissible non-symplectic index has the
##      form 2^a or 3*2^a.
##
##  This file contains executable code only.  Explanations and recorded
##  outputs are collected in gap_yyz_bounds.md.
##
##  The paper cites GAP 4.15.1.  The Small Groups Library is used.
##
#############################################################################


#############################################################################
##  1. User options
#############################################################################

PRINT_INDEX_SUMMARY := true;
PRINT_CANDIDATE_GROUPS := true;

# The original source file contained an additional output block produced by
# auxiliary product calculations, but did not record the exact invocation.
# The auxiliary data and functions are retained below.  Set this to true to
# run the selected auxiliary product calculation described in the README.
RUN_AUXILIARY_PRODUCT_CALCULATION := false;

if LoadPackage("smallgrp") = fail then
    Error("The GAP package smallgrp is required.");
fi;


#############################################################################
##  2. Group data
#############################################################################

# The scalar subgroup generated by the cubic scalar matrix.
ScalarGroup := Group([E(3) * IdentityMat(6)]);;

# Matrix realizations are needed for the 1st, 2nd, and 7th groups in the
# Yang-Yu-Zhu list of maximal automorphism groups.

# First maximal group.
mat1 := [
    [0,1,0,0,0,0], [1,0,0,0,0,0], [0,0,1,0,0,0],
    [0,0,0,1,0,0], [0,0,0,0,1,0], [0,0,0,0,0,1]
];;
mat2 := [
    [0,1,0,0,0,0], [0,0,1,0,0,0], [0,0,0,1,0,0],
    [0,0,0,0,1,0], [0,0,0,0,0,1], [1,0,0,0,0,0]
];;
mat3 := DiagonalMat([1,E(3),1,1,1,1]);;
H1Linear := Group([mat1, mat2, mat3]);;
H1 := H1Linear / ScalarGroup;;

# Second maximal group.
mat4 := [
    [0,1,0,0,0,0], [0,0,1,0,0,0], [1,0,0,0,0,0],
    [0,0,0,0,1,0], [0,0,0,0,0,1], [0,0,0,1,0,0]
];;
mat5 := [
    [1,0,0,0,0,0], [0,E(3),0,0,0,0], [0,0,E(3)^2,0,0,0],
    [0,0,0,0,1,0], [0,0,0,1,0,0], [0,0,0,0,0,1]
];;
mat6 := (1 / Sqrt(3)) * [
    [1,1,1,0,0,0], [1,E(3),E(3)^2,0,0,0],
    [1,E(3)^2,E(3),0,0,0], [0,0,0,E(3)*Sqrt(3),0,0],
    [0,0,0,0,Sqrt(3),0], [0,0,0,0,0,Sqrt(3)]
];;
H2Linear := Group([mat4, mat5, mat6]);;
H2 := H2Linear / ScalarGroup;;

# Seventh maximal group.
mat7 := DiagonalMat([1,E(3),E(3)^2,1,1,1]);;
mat8 := (1 / Sqrt(3)) * [
    [1,1,1,0,0,0], [1,E(3),E(3)^2,0,0,0],
    [1,E(3)^2,E(3),0,0,0], [0,0,0,Sqrt(3),0,0],
    [0,0,0,0,Sqrt(3),0], [0,0,0,0,0,Sqrt(3)]
];;
mat9 := [
    [0,0,0,0,1,0], [0,0,0,0,0,1], [0,0,0,1,0,0],
    [1,0,0,0,0,0], [0,1,0,0,0,0], [0,0,1,0,0,0]
];;
H7Linear := Group([mat7, mat8, mat9]);;
H7 := H7Linear / ScalarGroup;;

# The 15 maximal groups in Yang-Yu-Zhu, Theorem 1.2.
MaximalGroups := [
    H1,
    H2,
    SmallGroup(144,69),
    DirectProduct(SymmetricGroup(5), SmallGroup(18,3)),
    SmallGroup(48,2),
    SmallGroup(1980,57),
    H7,
    SmallGroup(32,1),
    SmallGroup(126,7),
    SmallGroup(720,765),
    SymmetricGroup(7),
    SmallGroup(32,42),
    SmallGroup(336,208),
    SmallGroup(48,29),
    SmallGroup(216,153)
];;

# The 34 symplectic automorphism groups in Laza-Zheng, Theorem 1.2.
# Their order agrees with the order used in Table 3 of arXiv:2606.11754v1.
G1 := NormalSubgroups(H1)[3];;
SymplecticGroups := [
    G1,
    AlternatingGroup(7),
    SmallGroup(1944,3559),
    SmallGroup(720,765),
    SmallGroup(660,13),
    SmallGroup(360,120),
    SmallGroup(972,776),
    SmallGroup(360,118),
    SmallGroup(168,42),
    SmallGroup(120,34),
    SmallGroup(72,41),
    SmallGroup(72,40),
    SmallGroup(48,29),
    SmallGroup(486,249),
    SmallGroup(72,43),
    SmallGroup(60,5),
    SmallGroup(36,9),
    SmallGroup(36,10),
    SmallGroup(21,1),
    SmallGroup(20,3),
    SmallGroup(16,8),
    SmallGroup(24,12),
    SmallGroup(8,4),
    SmallGroup(18,4),
    SmallGroup(12,4),
    SmallGroup(12,3),
    SmallGroup(10,1),
    SmallGroup(8,3),
    SmallGroup(4,1),
    SmallGroup(6,1),
    SmallGroup(4,2),
    SmallGroup(3,1),
    SmallGroup(2,1),
    SmallGroup(1,1)
];;

# Auxiliary maximal groups for cubic threefolds.  These are only needed for
# the optional product calculation at the end of this file.
MaximalCubicThreefoldGroups := [
    Group([
        [[0,1,0,0,0],[1,0,0,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,0,1]],
        [[0,1,0,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,0,1],[1,0,0,0,0]],
        DiagonalMat([E(3),1,1,1,1])
    ]) / Group([E(3) * IdentityMat(5)]),
    SmallGroup(648,713),
    SmallGroup(24,2),
    SmallGroup(16,1),
    SmallGroup(660,13),
    SmallGroup(360,119)
];;

# Auxiliary maximal groups for cubic surfaces, retained from the original
# source file.  They are not used by the main YYZ-bound calculation.
MaximalCubicSurfaceGroups := [
    SmallGroup(1,1),
    SmallGroup(2,1),
    SmallGroup(4,1),
    SmallGroup(8,1),
    SmallGroup(4,2),
    SmallGroup(6,1),
    SmallGroup(12,4),
    SmallGroup(24,12),
    SmallGroup(54,13),
    SmallGroup(108,36),
    SmallGroup(120,34),
    SmallGroup(648,704)
];;

# Change this assignment if the supplementary block is to be reconstructed
# from the cubic-surface list instead.  The original file did not record which
# auxiliary list was used for its final pasted output.
AuxiliaryBaseGroups := MaximalCubicThreefoldGroups;;


#############################################################################
##  3. Basic predicates and subgroup enumeration
#############################################################################

# Return true exactly for integers of the form 2^a or 3*2^a, a >= 0.
IsAllowedYYZIndex := function(n)
    local two_part;

    if not IsInt(n) or n < 1 then
        return false;
    fi;

    two_part := n;
    if two_part mod 3 = 0 then
        two_part := two_part / 3;
    fi;

    while two_part > 1 and two_part mod 2 = 0 do
        two_part := two_part / 2;
    od;

    return two_part = 1;
end;

# Return one representative for each isomorphism class of subgroups of G.
# Conjugacy classes are enumerated first, then representatives of the same
# order are compared for abstract isomorphism.
NonIsomorphicSubgroups := function(G)
    local representatives, result, candidate, known, duplicate;

    representatives := List(ConjugacyClassesSubgroups(G), Representative);
    result := [];

    for candidate in representatives do
        duplicate := false;

        for known in result do
            if Size(candidate) = Size(known)
               and IsomorphismGroups(candidate, known) <> fail then
                duplicate := true;
                break;
            fi;
        od;

        if not duplicate then
            Add(result, candidate);
        fi;
    od;

    return result;
end;

# Enumerate non-isomorphic subgroup representatives in each maximal group.
# The source maximal-group label is retained.  Normal subgroups are computed
# lazily and cached only when a candidate order can occur.
BuildCandidateRecords := function(maximal_groups)
    local records, maximal_label, subgroup;

    records := [];

    for maximal_label in [1..Length(maximal_groups)] do
        for subgroup in NonIsomorphicSubgroups(maximal_groups[maximal_label]) do
            Add(records, rec(
                group := subgroup,
                order := Size(subgroup),
                maximal_label := maximal_label
            ));
        od;
    od;

    return records;
end;

# Test whether G is isomorphic to a normal subgroup N of the candidate group
# and the quotient candidate/N is cyclic.  The index restriction is checked
# before the more expensive normal-subgroup and isomorphism computations.
HasNormalCyclicQuotient := function(G, candidate)
    local g_order, index, normal_subgroup, quotient;

    g_order := Size(G);

    if candidate.order mod g_order <> 0 then
        return false;
    fi;

    index := candidate.order / g_order;
    if not IsAllowedYYZIndex(index) then
        return false;
    fi;

    if not IsBound(candidate.normal_subgroups) then
        candidate.normal_subgroups := NormalSubgroups(candidate.group);
    fi;

    for normal_subgroup in candidate.normal_subgroups do
        if Size(normal_subgroup) = g_order
           and IsomorphismGroups(G, normal_subgroup) <> fail then
            quotient := FactorGroup(candidate.group, normal_subgroup);
            if IsCyclic(quotient) then
                return true;
            fi;
        fi;
    od;

    return false;
end;


#############################################################################
##  4. Main YYZ-bound calculation
#############################################################################

# Each output record is a list
#   [symplectic_label, index, candidate_full_group, maximal_group_label].
GenerateYYZCandidates := function(symplectic_groups, maximal_groups)
    local result, candidates, symplectic_label, G, candidate, index;

    result := [];
    candidates := BuildCandidateRecords(maximal_groups);

    for symplectic_label in [1..Length(symplectic_groups)] do
        G := symplectic_groups[symplectic_label];

        for candidate in candidates do
            if candidate.order >= Size(G)
               and HasNormalCyclicQuotient(G, candidate) then
                index := candidate.order / Size(G);
                Add(result, [
                    symplectic_label,
                    index,
                    candidate.group,
                    candidate.maximal_label
                ]);
            fi;
        od;
    od;

    return result;
end;

# Convert the detailed candidate list into one sorted index list for every
# symplectic group label.
SummarizeYYZIndices := function(candidates, number_of_groups)
    local summary, label, indices;

    summary := [];

    for label in [1..number_of_groups] do
        indices := Set(List(
            Filtered(candidates, entry -> entry[1] = label),
            entry -> entry[2]
        ));
        Add(summary, [label, SortedList(indices)]);
    od;

    return summary;
end;

# Keep only the divisibility-maximal elements.  These are the compact
# "YYZ bounds" shown in Table 3 of the paper.
DivisibilityMaximalElements := function(values)
    return Filtered(
        values,
        m -> not ForAny(values, n -> n <> m and n mod m = 0)
    );
end;


#############################################################################
##  5. Output formatting
#############################################################################

# Use SmallGroup identifiers when available in the range used by the original
# script.  Otherwise fall back to StructureDescription.
DescribeGroup := function(G)
    local order, id, description;

    order := Size(G);

    if order <= 2000 and order <> 1024 then
        id := IdGroup(G);
        return Concatenation(
            "[", String(id[1]), ",", String(id[2]), "]"
        );
    fi;

    description := StructureDescription(G);
    if description <> fail then
        return description;
    fi;

    return Concatenation(
        "Order ", String(order), ", abelian = ", String(IsAbelian(G))
    );
end;

PrintYYZIndexSummary := function(summary)
    local entry, label, candidates, bounds;

    for entry in summary do
        label := entry[1];
        candidates := entry[2];
        bounds := DivisibilityMaximalElements(candidates);

        Print(
            "G_", label,
            ": candidate indices = ", candidates,
            "; YYZ bounds = ", bounds, "\n"
        );
    od;
end;

# Warning: descriptions are deduplicated as strings.  Distinct groups can
# occasionally have the same StructureDescription.
PrintYYZCandidateGroups := function(candidates)
    local labels, label, entries, indices, index, descriptions, entry,
          description;

    labels := SortedList(Set(List(candidates, entry -> entry[1])));

    for label in labels do
        Print("G_", label, " candidate full groups:\n");
        entries := Filtered(candidates, entry -> entry[1] = label);
        indices := SortedList(Set(List(entries, entry -> entry[2])));

        for index in indices do
            Print("  index ", index, ":\n");
            descriptions := [];

            for entry in entries do
                if entry[2] = index then
                    description := DescribeGroup(entry[3]);
                    if not description in descriptions then
                        Add(descriptions, description);
                    fi;
                fi;
            od;

            for description in descriptions do
                Print("    ", description, "\n");
            od;
        od;
    od;
end;


#############################################################################
##  6. Auxiliary product calculation
#############################################################################

# Form direct products K x fixed_group, where K runs through one representative
# of every subgroup isomorphism class in the supplied group list.
SubgroupProducts := function(group_list, fixed_group)
    local result, ambient_group, subgroup;

    result := [];

    for ambient_group in group_list do
        if IsGroup(ambient_group) then
            for subgroup in NonIsomorphicSubgroups(ambient_group) do
                Add(result, DirectProduct(subgroup, fixed_group));
            od;
        fi;
    od;

    return result;
end;

# Pair groups only when the cyclic quotient index is 3*2^a.
GenerateThreePartPairs := function(list1, list2)
    local result, G1, G2, index, candidate;

    result := [];

    for G1 in list1 do
        for G2 in list2 do
            candidate := rec(group := G2, order := Size(G2));

            if HasNormalCyclicQuotient(G1, candidate) then
                index := Size(G2) / Size(G1);
                if index mod 3 = 0
                   and IsAllowedYYZIndex(index) then
                    Add(result, [G1, G2, index]);
                fi;
            fi;
        od;
    od;

    return result;
end;

PrintGroupPairings := function(triples)
    local grouped, triple, name, names, pairs, pair;

    if Length(triples) = 0 then
        Print("No auxiliary triples found.\n");
        return;
    fi;

    grouped := rec();

    for triple in triples do
        name := StructureDescription(triple[1]);
        if not IsBound(grouped.(name)) then
            grouped.(name) := [];
        fi;
        Add(grouped.(name), [triple[2], triple[3]]);
    od;

    names := RecNames(grouped);
    Sort(names);

    for name in names do
        Print(name, ":\n");
        pairs := grouped.(name);
        Sort(pairs, function(left, right)
            if left[2] <> right[2] then
                return left[2] < right[2];
            fi;
            return StructureDescription(left[1])
                   < StructureDescription(right[1]);
        end);

        for pair in pairs do
            Print(
                "  (", StructureDescription(pair[1]),
                ", ", pair[2], ")\n"
            );
        od;
        Print("\n");
    od;
end;


#############################################################################
##  7. Run the calculations
#############################################################################

YYZCandidates := GenerateYYZCandidates(SymplecticGroups, MaximalGroups);;
YYZIndexSummary := SummarizeYYZIndices(
    YYZCandidates,
    Length(SymplecticGroups)
);;

if PRINT_INDEX_SUMMARY then
    PrintYYZIndexSummary(YYZIndexSummary);
fi;

if PRINT_CANDIDATE_GROUPS then
    PrintYYZCandidateGroups(YYZCandidates);
fi;

if RUN_AUXILIARY_PRODUCT_CALCULATION then
    AuxiliaryProductGroups := SubgroupProducts(
        AuxiliaryBaseGroups,
        SmallGroup(3,1)
    );;
    AuxiliaryTriples := GenerateThreePartPairs(
        SymplecticGroups,
        AuxiliaryProductGroups
    );;
    PrintGroupPairings(AuxiliaryTriples);
fi;
